#!/usr/bin/env python3
"""Create GitHub issues from /tmp/issues.json using gh CLI."""
import json, subprocess, sys, time

sha    = open("/tmp/sha.txt").read().strip()
issues = json.load(open("/tmp/issues.json"))

if not issues:
    print("No issues found — push looks clean.")
    sys.exit(0)

print(f"Creating {len(issues)} issue(s)...")

for issue in issues:
    title    = issue.get("title", "Untitled issue")
    body     = issue.get("body", "")
    severity = issue.get("severity", "medium")
    labels   = issue.get("labels", ["bug"])

    full_title = f"[{severity}] {title}"
    full_body  = (
        f"**Found in commit:** `{sha}`\n\n"
        f"{body}\n\n"
        "---\n"
        "*Auto-generated by AI Issue Reporter (Kimi K2 via NVIDIA NIM)*"
    )

    # Try with labels first
    label_args = []
    for lbl in labels:
        label_args += ["--label", lbl]

    cmd = ["gh", "issue", "create", "--title", full_title, "--body", full_body] + label_args
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode == 0:
        print(f"✓ Created: {full_title}")
        print(f"  {result.stdout.strip()}")
    else:
        # Label might not exist in repo — retry without labels
        cmd2 = ["gh", "issue", "create", "--title", full_title, "--body", full_body]
        result2 = subprocess.run(cmd2, capture_output=True, text=True)
        if result2.returncode == 0:
            print(f"✓ Created (no label): {full_title}")
            print(f"  {result2.stdout.strip()}")
        else:
            print(f"✗ Failed to create: {full_title}", file=sys.stderr)
            print(f"  {result2.stderr.strip()}", file=sys.stderr)

    time.sleep(1)
